language: java
env:
  - GROOVY_VERSION=2.5.2
  - GROOVY_VERSION=2.6.0-alpha-4
script: ./gradlew clean check groovydoc assemble
jenkins:
  pipeline_jenkinsfile: .ci/Jenkinsfile
  stash:
    - name: artifacts
      matrix_axis:
        env: GROOVY_VERSION=2.5.2
    - name: html
      matrix_axis:
        env: GROOVY_VERSION=2.5.2
    - name: junit
      matrix_axis:
        env: GROOVY_VERSION=2.5.2
  collect:
    artifacts: build/libs/*.jar
    junit: build/test-results/**/*.xml
    html:
      path: build/docs/groovydoc
      reportName: 'groovy-gradle-seed API docs'
